language: cpp
os: osx
osx_image: xcode12.5
compiler: clang

before_install:
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
script:
- if [ "$TRAVIS_OS_NAME" == "osx"   ]; then cd "./Builds/MacOSX"; fi
- if [ "$TRAVIS_OS_NAME" == "osx"   ]; then xcodebuild -project vitOTT.xcodeproj ARCHS=x86_64 ONLY_ACTIVE_ARCH=NO -configuration Release build; fi
- cd ./../.. 

after_success:
- export VERSION=$(git describe --tags)
- if [ "$TRAVIS_OS_NAME" == "osx"   ]; then export DEPLOYFILE=vitOTT-$VERSION.dmg; fi
- if [ "$TRAVIS_OS_NAME" == "osx"   ]; then mkdir ./output; fi
- if [ "$TRAVIS_OS_NAME" == "osx"   ]; then cp -r ./Builds/MacOSX/build/Release/* ./output/; fi
- if [ "$TRAVIS_OS_NAME" == "osx"   ]; then hdiutil create /tmp/tmp.dmg -ov -volname "vitOTT-$VERSION" -fs HFS+ -srcfolder "./output/"; fi
- if [ "$TRAVIS_OS_NAME" == "osx"   ]; then hdiutil convert /tmp/tmp.dmg -format UDZO -o ./$DEPLOYFILE; fi
deploy:
  provider: releases
  api_key:
    secure: "kUHB7WEVDBe9E72kskIef/o2zfzsIx16oJV/MAwgbH5DbOdek3NLPTk9vkUMNFMD08Y/iZAK+roxUJrNwtjHl+eIy2szryx/NP9DN2OmjEj8w74CPG3D6OZR3x9VFsLMaLVhcmejD4fC1BHXKE1G7qO3N65PB4wX92P/nKJs1JVsM1Gg2xCbN4zpShMBLHI/+HOCxuWEvEJr1pA3KwLB8VTP6IlaIc+FtM6kJT+tSjF9jbv/F+ThlB1o0ek/c5M7bDCctK+qvO9zoGF4M5r8f89wLqfvlmNPbl10YTKoUgtbmFd3aI2BlguLX56+7q7hlW2wdA3lhqo9oZiXAgCo0b4sQUyESI+vxWT97+/jHPZATM42mx0BNeeQglPtauS1qoIAl98f4kCMcv+Q5ug+AhOpj/HiLAn6Gh4cC0z9Giu1z8sy73xrvlY1joYYXiWH1fzHagAhc07fHtY3pzCIP5dc43cwij1EblQcPYXeVCnTWl3Z4DjMHRqItkcJo2ucM4YXStdD/ObKFrVYR8sWwl2Duc0fqXgUd3QGiMTUf7v6s5oLZ0W/z10k3q3clYnhyA49hucQOvRxsOVpNpFs6kBh8KpDJ2YQfYzoKSuJiSsAiiVfPy7wJILv/75apDSsYdYXg0/uzaKF8pEM4ZhactF6uJXtWVdcnjWUpgofs3E="
  file: "$DEPLOYFILE"
  skip_cleanup: true
  on:
    repo: edgjj/vitOTT
    tags: true

