language: cpp
os: osx
osx_image: xcode12.5

before_install:
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
- wget -c -nv "https://github.com/juce-framework/JUCE/releases/download/6.0.8/juce-6.0.8-$TRAVIS_OS_NAME.zip"
- unzip ./juce-6.0.8-$TRAVIS_OS_NAME.zip -d $(SRCROOT)/~/

script:
- if [ "$TRAVIS_OS_NAME" == "osx"   ]; then cd "./Builds/MacOSX"; fi
- if [ "$TRAVIS_OS_NAME" == "osx"   ]; then xcodebuild -project vitOTT.xcodeproj ARCHS=x86_64 ONLY_ACTIVE_ARCH=NO -configuration Release build; fi
- cd ./../..

after_success:
- export VERSION=$(git describe --tags)
- if [ "$TRAVIS_OS_NAME" == "osx"   ]; then export DEPLOYFILE=sfizz-$VERSION.dmg; fi
- if [ "$TRAVIS_OS_NAME" == "osx"   ]; then mkdir ./output; fi
- if [ "$TRAVIS_OS_NAME" == "osx"   ]; then cp -r ./Builds/MacOSX/build/Release/* ./output/; fi
- if [ "$TRAVIS_OS_NAME" == "osx"   ]; then cp ./resources/icons/icon.icns ./output/sfizz.app/Contents/Resources/; fi
- if [ "$TRAVIS_OS_NAME" == "osx"   ]; then hdiutil create /tmp/tmp.dmg -ov -volname "sfizz-$VERSION" -fs HFS+ -srcfolder "./output/"; fi
- if [ "$TRAVIS_OS_NAME" == "osx"   ]; then hdiutil convert /tmp/tmp.dmg -format UDZO -o ./$DEPLOYFILE; fi