name: Builds

on: [push, pull_request]

jobs:
  do-builds:
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-11]

    name: Build plugin & upload artifacts
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
              sudo apt-get update 
              sudo apt install libasound2-dev libjack-jackd2-dev \
                libfreetype6-dev \
                libx11-dev libxcomposite-dev libxcursor-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libxrender-dev \
                libglu1-mesa-dev mesa-common-dev

      - name: Run CMake (OSX/Linux)
        if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macos')
        run: |
              mkdir build && cd build
              cmake -DCMAKE_CXX_FLAGS="-ffast-math -O3" ..
              cmake --build . --config Release
            
      - name: Run CMake (Windows)
        if: startsWith(matrix.os, 'windows')
        run: |
              mkdir build && cd build
              cmake -DCMAKE_CXX_FLAGS="/Ox /fp:fast" ..
              cmake --build . --config Release
      
      - name: Validate plugin (Windows)
        if: startsWith(matrix.os, 'windows')
        run: |
              powershell -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-WebRequest https://github.com/Tracktion/pluginval/releases/latest/download/pluginval_Windows.zip -OutFile pluginval.zip"
              powershell -Command "Expand-Archive pluginval.zip -DestinationPath ."
              pluginval.exe --validate-in-process --skip-gui-tests --strictness-level 5 "build/vitOTT_artefacts/Release/VST3/vitOTT.vst3"
              if %ERRORLEVEL% neq 0 exit /b 1 
        shell: cmd

      - name: Validate plugin (OSX)
        if: startsWith(matrix.os, 'macos')
        run: |
              curl -L "https://github.com/Tracktion/pluginval/releases/latest/download/pluginval_macOS.zip" -o pluginval.zip
              unzip pluginval
              killall -9 AudioComponentRegistrar
              pluginval.app/Contents/MacOS/pluginval --skip-gui-tests --validate-in-process --strictness-level 5 "build/vitOTT_artefacts/VST3/vitOTT.vst3" || exit 1
              pluginval.app/Contents/MacOS/pluginval --skip-gui-tests --validate-in-process --strictness-level 5 build/vitOTT_artefacts/AU/vitOTT.component || exit 1

      - name: Validate plugin (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
              curl -L "https://github.com/Tracktion/pluginval/releases/latest/download/pluginval_Linux.zip" -o pluginval.zip
              unzip pluginval
              ./pluginval --validate-in-process --skip-gui-tests --strictness-level 5 "build/vitOTT_artefacts/VST3/vitOTT.vst3" || exit 1

      - uses: actions/upload-artifact@v3
        if: startsWith(matrix.os, 'ubuntu')
        with: 
          name: vitOTT-linux-x86_64-lv2_vst3
          path: | 
                 build/vitOTT_artefacts/VST3
                 build/vitOTT_artefacts/LV2

      - uses: actions/upload-artifact@v3
        if: startsWith(matrix.os, 'macos')
        with: 
          name: vitOTT-osx-x86_64-au_vst3
          path: | 
                 build/vitOTT_artefacts/VST3
                 build/vitOTT_artefacts/AU

      - uses: actions/upload-artifact@v3
        if: startsWith(matrix.os, 'windows')
        with: 
          name: vitOTT-windows-x86_64-vst3
          path: |
                 build/vitOTT_artefacts/Release/VST3
                 !build/vitOTT_artefacts/Release/VST3/*.exp
                 !build/vitOTT_artefacts/Release/VST3/*.lib
