name: Builds

on: [push, pull_request]

jobs:
  do-builds:
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-11]

    name: Build plugin & upload artifacts
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: |
              sudo apt-get update 
              sudo apt-get install -y libasound2-dev libgtk-3-dev libxcb1-dev libcurl4-openssl-dev libwebkit2gtk-4.0-dev
      
      - name: Run CMake
        if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macos')
        run: |
              mkdir build && cd build
              cmake -DCMAKE_CXX_FLAGS="-ffast-math -O3" ..
              cmake --build . --config Release
            
      - name: Run CMake
        if: startsWith(matrix.os, 'windows')
        run: |
              mkdir build && cd build
              cmake -DCMAKE_CXX_FLAGS="/Ox /fp:fast" ..
              cmake --build . --config Release
      
      - uses: actions/upload-artifact@v3
        if: startsWith(matrix.os, 'ubuntu')
        with: 
          name: vitOTT-linux-x86_64-lv2_vst3
          path: build/vitOTT_artefacts/

      - uses: actions/upload-artifact@v3
        if: startsWith(matrix.os, 'macos')
        with: 
          name: vitOTT-osx-x86_64-au_vst3
          path: build/vitOTT_artefacts/

      - uses: actions/upload-artifact@v3
        if: startsWith(matrix.os, 'windows')
        with: 
          name: vitOTT-windows-x86_64-vst3
          path: build/vitOTT_artefacts/Release/
